### ISSUE TITLE
Need new maintainer

### ISSUE THREAD

**Issue by dmerejkowsky** [SuperTanker/homebrew-repo#11]
I no longer have access to Apple hardware, so I won't be able to maintain the recipes that are present here.

@maximerety : I can transfer the repo to you if you feel like maintaining it :)

**Comment by maximerety** [comment]
I'd recommend that you don't transfer the repo.

It would be clearer to keep your repos and brew formulas under the same GitHub user. There seem to be an implicit link between them as explained [in the docs](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#installing). For example, calling `brew install dmerejkowsky/ruplacer/formula` automatically resolves and adds the tap `dmerejkowsky/homebrew-repo` before installing the formula.

I'd suggest you add me as a maintainer on this repo instead, and I'll see what I can do to update the formula 😊  (or don't and I'll make a PR from a fork, that would work too!).

What do you think?

**Comment by dmerejkowsky** [comment]
I'm always happy to get new co-maintainers - let's do it your way :)
