### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by Masynchin** [SuperTanker/homebrew-repo#13]
I barely missed ruplacer updates. 0.8.0 is the latest version, but only 0.6.4 available in brew.

@maximerety, can you update formulae? Also, I do some research and found [this action](https://github.com/dawidd6/action-homebrew-bump-formula) for auto-bumping brew package version. I haven't work with this action, but hope it will be helpful for you.

**Comment by maximerety** [comment]
Thanks for sharing.

I'm not sure I'll have time to review this package soon, but in the meantime I've subscribed to releases on the [ruplacer repository](https://github.com/dmerejkowsky/ruplacer) so I can update the formula in a timely manner.

Just posted PR https://github.com/dmerejkowsky/homebrew-repo/pull/14 to update the formula with version 0.8.0.

**Comment by dmerejkowsky** [comment]
> I've subscribed to releases on the [ruplacer repository](https://github.com/dmerejkowsky/ruplacer) so I can update the formula in a timely manner.

Good idea ;)

**Comment by maximerety** [comment]
Closing due to merge of PR https://github.com/dmerejkowsky/homebrew-repo/pull/14.
