### ISSUE TITLE
Problem installing it from brew

### ISSUE THREAD

**Issue by gianvitom** [SuperTanker/homebrew-repo#6]
I had this problem trying to install it from brew running 'brew install TankerHQ/homebrew-repo/ruplacer':

==> Installing ruplacer from tankerhq/repo
==> Downloading https://github.com/TankerHQ/ruplacer/archive/v0.3.0.tar.gz
Already downloaded: /Users/gianvito/Library/Caches/Homebrew/downloads/86a3c8a1ae613fa24cfd34c9a35d29e7de3ad3bd3b689dc8ffc5149164dbdc57--ruplacer-0.3.0.tar.gz
==> cargo install --root /usr/local/Cellar/ruplacer/0.3.0 --path .
Last 15 lines from /Users/gianvito/Library/Logs/Homebrew/ruplacer/01.cargo:
/usr/local/Cellar/ruplacer/0.3.0
--path
.

  Installing ruplacer v0.3.0 (/private/tmp/ruplacer-20190414-54803-kscnql/ruplacer-0.3.0)
 Downloading crates ...
warning: spurious network error (2 tries remaining): failed to get 200 response from `https://static.crates.io/crates/same-file/same-file-1.0.3.crate`, got 504
warning: spurious network error (1 tries remaining): failed to get 200 response from `https://static.crates.io/crates/same-file/same-file-1.0.3.crate`, got 504
error: failed to compile `ruplacer v0.3.0 (/private/tmp/ruplacer-20190414-54803-kscnql/ruplacer-0.3.0)`, intermediate artifacts can be found at `/private/tmp/ruplacer-20190414-54803-kscnql/ruplacer-0.3.0/target`

Caused by:
  failed to download from `https://crates.io/api/v1/crates/same-file/1.0.3/download`

Caused by:
  failed to get 200 response from `https://static.crates.io/crates/same-file/same-file-1.0.3.crate`, got 504

**Comment by dmerejkowsky** [comment]
Hello and thanks for the detailed bug report.

It looks like an issue on crates.io (error 504). Can you please retry?

Alternatively, you could try using cargo directly:

```
cargo install ruplacer
```

or just use the [archive containing the pre-compiled binary](https://github.com/TankerHQ/ruplacer/releases/download/v0.4.1/ruplacer-v0.4.1-macos.tar.gz).

Cheers!

Come to think of it, maybe the brew recipe should use the aforementioned achive instead.

**Comment by gianvitom** [comment]
I retried with brew and now it works, thank you!
